### ISSUE TITLE
Générer un hash MD5 des fichiers dans le index.json

### ISSUE THREAD

**Issue by FlyzZx** [FlyzZx/BOWKmeansTrainerSVM#4]
Generer un hash md5 du vocab + classifiers dans le index.json pour les versionner de facon non ordonnée

**Comment by nicolasfaraci** [comment]
Je m'en occupe

**Comment by nicolasfaraci** [comment]
Terminé, je place un hash du fichier vocabulaire dans index.json sous la clée vocab_hash. Un fonction pour récupérer le hash d'un fichier est présente dans la classe LogoFinder, y'a juste a mettre à jour cette classe cote android et a checker si le hash a changer en récupérant juste index.json. SI oui, on retélécharge tout.
Résolu par https://github.com/FlyzZx/BOWKmeansTrainerSVM/commit/38d7d7f9db9c448c5562974c0502028a41be6587
